networks:
  internal:
    driver: bridge

services:
  flask:
    build: .
    network_mode: host
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
    volumes:
      #- ./data:/app/data
      - ./.env:/app/.env

  nginx:
    image: nginx:1.21-alpine
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/nginx/cache:/etc/nginx/cache
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./site:/srv
      - ./data/.htpasswd:/etc/nginx/.htpasswd:ro
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      -  internal

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - internal
